version: 2
jobs:
  build:
    docker:
      # See docker/Dockerfile
      - image: feedreader/fedora-feedreader-devel
        environment:
          # Note: The Feedbin API has to run on subdomain "api"
          FEEDBIN_TEST_HOST: http://api.x.localhost:9292
      # See docker/Dockerfile.Feedbin
      - image: feedreader/feedbin
        environment:
          ELASTICSEARCH_URL: http://127.0.0.1:9200
          POSTGRES_USERNAME: postgres
          POSTGRES_HOST: 127.0.0.1
          DATABASE_URL: postgres://postgres@127.0.0.1:5432/feedbin_db
          REDIS_URL: redis://127.0.0.1:6379
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
        environment:
          'discovery.type': single-node
      - image: postgres:9.6.5-alpine
      - image: redis:3.2.11-alpine

    working_directory: ~/FeedReader
    steps:
      - checkout
      - run:
          name: Build
          command: |
              cmake . -DBAZQUX=ON -DFEEDHQ=ON
              make
      - run:
          name: Test
          command: make test
      - run:
          name: Generate JUnit XML
          command: |
              mkdir -p /tmp/test-results/junit/
              for f in *.gtester.log; do
                  xsltproc -o /tmp/test-results/junit/$(basename $f .gtester.log).xml gtester-to-junit-4.xsl $f;
              done
          when: always
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results/junit
          destination: test-results
